### ISSUE TITLE
Adding s390x support to che-cert-manager-ca-cert-generator-image

### ISSUE THREAD

**Issue by prabhav-thali** [che-dockerfiles/che-cert-manager-ca-cert-generator-image#6]
As quay.io supports multi-arch images, we would like to extend s390x support for CI. Could you please provide some info about the CI process?

**Comment by ericwill** [comment]
We are in the process of converting all plugin sidecars to multi-arch support, using docker buildx. I am currently working on a [PR](https://github.com/che-dockerfiles/che-sidecar-vale/pull/8) for che-sidecar-vale which will eventually be applied to all repos in che-dockerfiles.

**Comment by prabhav-thali** [comment]
@ericwill That's Great! Please let us know if you need any assistance from our side, we can help to test on s390x architecture. Will keep this issue open till multi-arch images are available.

**Comment by prabhav-thali** [comment]
@ericwill any update on adding multi-arch support using docker buildx?

**Comment by ericwill** [comment]
> @ericwill any update on adding multi-arch support using docker buildx?

It's an ongoing process. Are you looking for any repos specifically (i.e. this one)?

**Comment by ericwill** [comment]
Looking at this again, the use-case is a bit different than our plugin sidecar repos. I think in this instance @mmorhun might be able to help you.

**Comment by mmorhun** [comment]
I think that the support for building on s390x architecture was added in https://github.com/che-dockerfiles/che-cert-manager-ca-cert-generator-image/pull/5. As about pushing built image to quay.io I am afraid I cannot help here as, AFAIK, CentOS CI doesn't have s390x nodes (and I have no admin rights there).

**Comment by prabhav-thali** [comment]
@ericwill @mmorhun Thanks for providing clarity. We have already started raising PRs in various repositories of Eclipse Che for instance [#109](https://github.com/eclipse/che-machine-exec/pull/109) for che-machine-exec. We are adding support for s390x in CICO scripts using docker buildx. Should we proceed the same way for che-cert-manager-ca-cert-generator-image?

**Comment by mmorhun** [comment]
I don't think that this image is different from others. But I don't see (maybe I just don't know something) how we can build s390x images on our CI (build process requires hardware).
As about the image itself, it is used with Helm installer only. So if you use operator/olm installer, you may just skip it.
